package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func cmdInit(args []string) {
	fs := newFlagSet("init")
	dir := fs.String("dir", ".", "directory to initialise")
	lang := fs.String("lang", "go", "instrument language: go or rust")
	name := fs.String("name", "", "package name (default: directory name)")
	route := fs.String("route", "", "route path (default: /<name>)")
	category := fs.String("category", "Custom", "category shown in the UI")
	desc := fs.String("desc", "", "short description")
	force := fs.Bool("force", false, "overwrite existing scaffold files")
	fs.Parse(args) //nolint:errcheck

	absDir, err := filepath.Abs(*dir)
	if err != nil {
		fatalf("resolve dir: %v", err)
	}
	base := filepath.Base(absDir)
	if *name == "" {
		*name = base
	}
	if *route == "" {
		*route = "/" + slugify(*name)
	}
	if err := os.MkdirAll(absDir, 0o755); err != nil {
		fatalf("create dir: %v", err)
	}

	manifest := &Manifest{
		Name:     *name,
		Version:  "0.1.0",
		Language: strings.ToLower(*lang),
		Module: ManifestModule{
			Source: slugify(*name) + ".wasm",
		},
		Route: ManifestRoute{Path: *route, Methods: []string{"GET"}},
		Metadata: ManifestMetadata{
			Category:    *category,
			Description: *desc,
			UseCase:     "Generated by wasio init.",
		},
		Examples:     []ManifestExample{{Label: "Default", Query: ""}},
		Capabilities: ManifestCapabilities{Names: []string{"wasi:stdio", "wasi:env"}},
	}

	switch strings.ToLower(*lang) {
	case "go", "tinygo":
		manifest.Module.Build = fmt.Sprintf("tinygo build -o %s -target wasi main.go", manifest.Module.Source)
		writeScaffoldFile(filepath.Join(absDir, "main.go"), goInstrumentTemplate(*name), *force)
	case "rust":
		manifest.Module.Build = fmt.Sprintf("cargo build --target wasm32-wasip1 --release && cp target/wasm32-wasip1/release/%s.wasm %s", slugify(*name), manifest.Module.Source)
		writeScaffoldFile(filepath.Join(absDir, "Cargo.toml"), rustCargoTemplate(*name), *force)
		if err := os.MkdirAll(filepath.Join(absDir, "src"), 0o755); err != nil {
			fatalf("create src dir: %v", err)
		}
		writeScaffoldFile(filepath.Join(absDir, "src", "main.rs"), rustInstrumentTemplate(*name), *force)
	default:
		fatalf("unsupported --lang %q (expected go or rust)", *lang)
	}

	manifestPath := filepath.Join(absDir, "wasio.toml")
	if _, err := os.Stat(manifestPath); err == nil && !*force {
		fatalf("%s already exists (use --force to overwrite)", manifestPath)
	}
	if err := SaveManifest(manifestPath, manifest); err != nil {
		fatalf("write manifest: %v", err)
	}

	fmt.Printf("✓ initialised WASIO package in %s\n", absDir)
	fmt.Printf("  manifest: %s\n", manifestPath)
	fmt.Printf("  route:    %s\n", manifest.Route.Path)
}

func cmdPull(args []string) {
	fs := newFlagSet("pull")
	configPath := fs.String("config", "config.json", "path to config file")
	force := fs.Bool("force", false, "overwrite existing route/file")
	requireSignature := fs.Bool("require-signature", false, "fail if the manifest has no valid signature")
	publicKeyFile := fs.String("public-key", "", "path to base64-encoded ed25519 public key override")
	fs.Parse(args) //nolint:errcheck

	source := fs.Arg(0)
	if source == "" {
		source = "wasio.toml"
	}

	manifest, manifestBase := loadManifestSource(source)

	var publicKey []byte
	var err error
	if *publicKeyFile != "" {
		publicKey, err = ReadKeyFile(*publicKeyFile)
		if err != nil {
			fatalf("read public key: %v", err)
		}
	}
	if manifest.Signature != nil || *requireSignature {
		if err := manifest.VerifyCapabilities(publicKey); err != nil {
			fatalf("verify manifest signature: %v", err)
		}
		fmt.Println("✓ manifest capability signature verified")
	} else {
		fmt.Println("! warning: manifest is unsigned")
	}

	cfg, err := LoadConfig(*configPath)
	if err != nil {
		fatalf("load config: %v", err)
	}
	if _, exists := cfg.Routes[manifest.Route.Path]; exists && !*force {
		fatalf("route %s already exists in %s (use --force to overwrite)", manifest.Route.Path, *configPath)
	}

	moduleSource, err := ResolveManifestSource(manifestBase, manifest.Module.Source)
	if err != nil {
		fatalf("resolve module source: %v", err)
	}
	destWASM := filepath.Join("instruments", InstallFilenameFromSource(moduleSource, manifest.Name))
	copyOrDownload(moduleSource, destWASM)

	cfg.Routes[manifest.Route.Path] = ManifestToRoute(manifest, destWASM)
	writeConfig(*configPath, cfg)

	if path, err := StoreManifestCopy(filepath.Join(".wasio", "manifests"), manifest); err == nil {
		fmt.Printf("✓ stored manifest copy at %s\n", path)
	}
	fmt.Printf("✓ installed %s %s at %s\n", manifest.Name, manifest.Version, manifest.Route.Path)
	fmt.Printf("  wasm:   %s\n", destWASM)
	fmt.Printf("  reload: ./wasio reload %s\n", manifest.Route.Path)
}

func cmdKeygen(args []string) {
	fs := newFlagSet("keygen")
	out := fs.String("out", "wasio-signing", "output prefix for .pub and .key files")
	fs.Parse(args) //nolint:errcheck

	pub, priv, err := GenerateKeyPair()
	if err != nil {
		fatalf("generate keypair: %v", err)
	}
	if err := WriteKeyFile(*out+".pub", pub); err != nil {
		fatalf("write public key: %v", err)
	}
	if err := WriteKeyFile(*out+".key", priv); err != nil {
		fatalf("write private key: %v", err)
	}
	fmt.Printf("✓ wrote %s.pub and %s.key\n", *out, *out)
}

func cmdSign(args []string) {
	fs := newFlagSet("sign")
	privateKeyFile := fs.String("private-key", "", "path to base64-encoded ed25519 private key")
	keyID := fs.String("key-id", "default", "key identifier stored in the manifest")
	fs.Parse(args) //nolint:errcheck

	manifestPath := fs.Arg(0)
	if manifestPath == "" {
		manifestPath = "wasio.toml"
	}
	if *privateKeyFile == "" {
		fatalf("--private-key is required")
	}

	manifest, err := LoadManifest(manifestPath)
	if err != nil {
		fatalf("load manifest: %v", err)
	}
	keyBytes, err := ReadKeyFile(*privateKeyFile)
	if err != nil {
		fatalf("read private key: %v", err)
	}
	if len(keyBytes) != 64 {
		fatalf("private key must be 64 raw ed25519 bytes")
	}
	if err := manifest.SignCapabilities(keyBytes, *keyID); err != nil {
		fatalf("sign manifest: %v", err)
	}
	if err := SaveManifest(manifestPath, manifest); err != nil {
		fatalf("write manifest: %v", err)
	}
	fmt.Printf("✓ signed capability declaration in %s\n", manifestPath)
}

func loadManifestSource(source string) (*Manifest, string) {
	if strings.HasPrefix(source, "http://") || strings.HasPrefix(source, "https://") {
		data, err := DownloadBytes(source)
		if err != nil {
			fatalf("download manifest: %v", err)
		}
		manifest, err := LoadManifestFromBytes(data)
		if err != nil {
			fatalf("load manifest: %v", err)
		}
		return manifest, source
	}
	manifestPath, err := filepath.Abs(source)
	if err != nil {
		fatalf("resolve manifest path: %v", err)
	}
	manifest, err := LoadManifest(manifestPath)
	if err != nil {
		fatalf("load manifest: %v", err)
	}
	return manifest, manifestPath
}

func copyOrDownload(source, dest string) {
	if strings.HasPrefix(source, "http://") || strings.HasPrefix(source, "https://") {
		fmt.Printf("downloading %s → %s\n", source, dest)
		if err := downloadFile(source, dest); err != nil {
			fatalf("download wasm: %v", err)
		}
		return
	}
	fmt.Printf("copying %s → %s\n", source, dest)
	if err := copyFile(source, dest); err != nil {
		fatalf("copy wasm: %v", err)
	}
}

func writeConfig(path string, cfg *Config) {
	data, err := jsonMarshalIndent(cfg)
	if err != nil {
		fatalf("serialise config: %v", err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		fatalf("write config: %v", err)
	}
}

func writeScaffoldFile(path, content string, force bool) {
	if _, err := os.Stat(path); err == nil && !force {
		fatalf("%s already exists (use --force to overwrite)", path)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		fatalf("write %s: %v", path, err)
	}
}

func goInstrumentTemplate(name string) string {
	return fmt.Sprintf(`package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"strings"
)

type payload struct {
	Params map[string]string `+"`json:\"params\"`"+`
}

func main() {
	scanner := bufio.NewScanner(os.Stdin)
	var in strings.Builder
	for scanner.Scan() {
		in.WriteString(scanner.Text())
	}
	var p payload
	_ = json.Unmarshal([]byte(in.String()), &p)
	guestName := p.Params["name"]
	if guestName == "" {
		guestName = "World"
	}
	fmt.Printf("{\"message\":\"Hello, %s!\"}", guestName)
}
`, name)
}

func rustCargoTemplate(name string) string {
	return fmt.Sprintf(`[package]
name = %q
version = "0.1.0"
edition = "2021"

[[bin]]
name = %q
path = "src/main.rs"

[profile.release]
opt-level = "s"
lto = true
strip = true
`, slugify(name), slugify(name))
}

func rustInstrumentTemplate(name string) string {
	return fmt.Sprintf(`use std::io::{self, Read};

fn main() {
    let mut input = String::new();
    let _ = io::stdin().read_to_string(&mut input);
    println!("{{\"message\":\"Hello from %s\",\"input_bytes\":{}}}", input.len());
}
`, name)
}

func newFlagSet(name string) *flag.FlagSet {
	return flag.NewFlagSet(name, flag.ExitOnError)
}

func jsonMarshalIndent(v interface{}) ([]byte, error) {
	return json.MarshalIndent(v, "", "  ")
}

func fatalf(format string, args ...interface{}) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
